# Generated by Django 5.2 on 2025-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('Admin', 'admin'), ('Cashier', 'cashier')], max_length=10),
        ),
    ]
