# Generated by Django 5.2 on 2025-05-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_account_type'),
    ]

    operations = [
    ]
