# Generated by Django 5.2 on 2025-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250521_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
