# Generated by Django 4.2.20 on 2025-05-11 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_description_alter_saleitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
