# Generated by Django 4.2.20 on 2025-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_image_item_supplier_item_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('pack', 'Pack'), ('case', 'Case'), ('pieces', 'Pieces'), ('meter', 'Meter'), ('liter', 'Liter'), ('kilograms', 'Kilograms'), ('pound', 'Pound'), ('gallons', 'Gallons')], max_length=100),
        ),
    ]
