# Generated by Django 4.2.20 on 2025-05-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], max_length=10),
        ),
    ]
