# Generated by Django 4.2 on 2025-04-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
    ]
