# Generated by Django 4.2 on 2025-04-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sale_item_remove_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
